- hosts: all
  vars:
    usuarios:
      - operador1
      - operador2
      - operador3
  tasks:
    - name: Create Group
      group:
        name: operadores
        state: present
    - name: Create Users
      user:
        name: "{{ item }}"
        groups: operadores
        state: present
      with_items: "{{ usuarios }}"
    - name: Install Auth Key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '/home/pue/.ssh/id_ed25519.pub') }}"
      with_items: "{{ usuarios }}"
